name: 'Folk Archive'
description: 'Acquires and runs Folk Archive archive builder'
inputs:
  archive_dir:
    description: 'Directory containing archival data'
    required: true
    default: 'content'
  theme_dir:
    description: 'Directory containing the site theme data'
    required: true
    default: 'site'
runs:
  using: 'docker'
  image: 'Dockerfile'
  volumes:
    - ${{ inputs.archive_dir }}:/content
    - ${{ inputs.theme_dir }}:/site
  args:
    - ${{ inputs.archive_dir }}
    - ${{ inputs.theme_dir }}
